# Generated by Django 5.1.6 on 2025-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_feedback_image_alter_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_images/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
