# Generated by Django 6.0.4 on 2026-04-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_alter_feedback_image_alter_feedback_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.itemlist'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
