# Generated by Django 6.0.4 on 2026-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_alter_items_category_alter_items_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='category_type',
            field=models.CharField(choices=[('food', 'Food'), ('snack', 'Snack')], default='food', max_length=10),
        ),
    ]
